/*
 * generated by Xtext 2.22.0
 */
package at.ac.tuwien.big.ui.tests;

import com.google.inject.Injector;
import cpsml.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class CpsmlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("at.ac.tuwien.big.Cpsml");
	}

}
