/*
 * generated by Xtext 2.27.0
 */
package at.ac.tuwien.big.scoping;

import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */


public class CpsmlScopeProvider extends AbstractDeclarativeScopeProvider {
	
	
}
